"""The JSON Schema of what chunkmirage exchanges: pipeline specs, each op's parameters, and
the query of a ``register://`` URL.

This is the one definition both engines share. The browser engine (``web/``) generates its
TypeScript types and form defaults from it (``chunkmirage schema --out ...``), and a test
keeps its committed copy current, so a change here shows up on both sides at once.
"""

from __future__ import annotations

import json
from typing import Any

from pydantic.json_schema import GenerateJsonSchema, models_json_schema

SCHEMA_DRAFT = "https://json-schema.org/draft/2020-12/schema"


class _Titled(GenerateJsonSchema):
    """Models keep their titles (the types' names); fields' titles would only become one-use
    type aliases in the generated TypeScript."""

    def field_title_should_be_set(self, schema) -> bool:
        return False


def spec_schema() -> dict[str, Any]:
    """One schema whose ``$defs`` hold every model: ``PipelineSpec``, ``RegisterParams``,
    ``StitchParams``, one per registered op (tagged with its ``op`` name), and ``OpSpec``, the union of them."""
    from chunkmirage.ops.base import get_op, list_ops
    from chunkmirage.pipeline import PipelineSpec
    from chunkmirage.sources.register import RegisterParams
    from chunkmirage.stitching import StitchParams

    ops = {name: get_op(name) for name in list_ops()}
    models = [PipelineSpec, RegisterParams, StitchParams, *ops.values()]
    _, top = models_json_schema([(m, "validation") for m in models], schema_generator=_Titled)
    defs = top["$defs"]
    for name, cls in ops.items():
        schema = defs[cls.__name__]
        schema["properties"] = {"op": {"const": name}, **schema.get("properties", {})}
        schema["required"] = ["op", *schema.get("required", [])]
    defs["OpSpec"] = {
        "title": "OpSpec",
        "description": "One entry of a pipeline's ops: an op's name and its parameters.",
        "oneOf": [{"$ref": f"#/$defs/{cls.__name__}"} for cls in ops.values()],
    }
    return {
        "$schema": SCHEMA_DRAFT,
        "title": "Chunkmirage",
        "description": "What chunkmirage exchanges; generated by `chunkmirage schema`.",
        "type": "object",
        "properties": {
            "pipeline": {"$ref": "#/$defs/PipelineSpec"},
            "register": {"$ref": "#/$defs/RegisterParams"},
            "stitch": {"$ref": "#/$defs/StitchParams"},
            "op": {"$ref": "#/$defs/OpSpec"},
        },
        "$defs": dict(sorted(defs.items())),
    }


def dumps() -> str:
    return json.dumps(spec_schema(), indent=2) + "\n"
