"""The JSON Schema of what chunkmirage exchanges: pipeline specs, each op's parameters, and
the query of a ``register://`` URL.

This is the one definition both engines share. The browser engine (``web/``) generates its
TypeScript types and form defaults from it (``chunkmirage schema --out ...``), and a test
keeps its committed copy current, so a change here shows up on both sides at once.
"""

from __future__ import annotations

import json
from typing import Any

SCHEMA_DRAFT = "https://json-schema.org/draft/2020-12/schema"


def spec_schema() -> dict[str, Any]:
    """One schema whose ``$defs`` hold every model: ``PipelineSpec``, ``RegisterParams``,
    one per registered op (tagged with its ``op`` name), and ``OpSpec``, the union of them."""
    from chunkmirage.ops.base import list_ops
    from chunkmirage.pipeline import PipelineSpec
    from chunkmirage.sources.register import RegisterParams

    defs: dict[str, Any] = {}

    def add(schema: dict[str, Any]) -> str:
        schema = dict(schema)
        defs.update(schema.pop("$defs", {}))
        # a model keeps its title (the type's name); its fields' titles would only become
        # one-use type aliases in the generated TypeScript
        schema["properties"] = {
            k: {a: b for a, b in v.items() if a != "title"}
            for k, v in schema.get("properties", {}).items()
        }
        defs[schema["title"]] = schema
        return schema["title"]

    pipeline = add(PipelineSpec.model_json_schema())
    register = add(RegisterParams.model_json_schema())
    ops = {}
    for name, meta in list_ops().items():
        schema = dict(meta["schema"])
        schema["properties"] = {"op": {"const": name}, **schema.get("properties", {})}
        schema["required"] = ["op", *schema.get("required", [])]
        if meta["doc"]:
            schema["description"] = meta["doc"]
        ops[name] = add(schema)
    defs["OpSpec"] = {
        "title": "OpSpec",
        "description": "One entry of a pipeline's ops: an op's name and its parameters.",
        "oneOf": [{"$ref": f"#/$defs/{title}"} for title in ops.values()],
    }
    return {
        "$schema": SCHEMA_DRAFT,
        "title": "Chunkmirage",
        "description": "What chunkmirage exchanges; generated by `chunkmirage schema`.",
        "type": "object",
        "properties": {
            "pipeline": {"$ref": f"#/$defs/{pipeline}"},
            "register": {"$ref": f"#/$defs/{register}"},
            "op": {"$ref": "#/$defs/OpSpec"},
        },
        "$defs": dict(sorted(defs.items())),
    }


def dumps() -> str:
    return json.dumps(spec_schema(), indent=2) + "\n"
